### ISSUE TITLE
UCI port tracker

### ISSUE THREAD

**Issue by mehmetseckin** [onurmenal/crm-power-pane#91]
This is a collection of obvious problems surfaced during the first attempt to port the extension to UCI.

- [x] Entity Info - "entity type code" is null ([`624052`](https://github.com/onurmenal/crm-power-pane/commit/624052153a19969e8e78f866314541e7801aebf9))
- [x] Record Properties ([`ed1deb`](https://github.com/onurmenal/crm-power-pane/commit/ed1deba8d0b95596ef61c3bca28ac227227a66a5))
- [x] Schema Name Copy Mode ([`508445`](https://github.com/onurmenal/crm-power-pane/commit/5084454f80432dc9729217684af75ce30372836a))
- [x] Show Option Set Values ([`a6d168`](https://github.com/onurmenal/crm-power-pane/commit/a6d1683a2fd9c5e2dffafa7b40ceba910345b530))
- [x] Highlight Dirty Fields ([`d35d71`](https://github.com/onurmenal/crm-power-pane/commit/d35d713176a788b5a7295b9a29554efa8a688b66))
- [x] Entity Editor ([`bca56e`](https://github.com/onurmenal/crm-power-pane/commit/bca56ec9e77e9ff0fb943ab735ec929c595a371d))
- [ ] ~~Mobile Express - goes to the home page for the organisation~~
- [ ] ~~Mobile Client - gets stuck at loading (?)~~

**Comment by mehmetseckin** [comment]
@onurmenal Mobile Express is [deprecated for versions after 2016](https://docs.microsoft.com/en-us/dynamics365/mobile-app/v8/set-up-manage/support#version-support), so no point trying to port that action to UCI.

I'm not sure about the other client, but I think we can leave it for a beta release. What do you think?

**Comment by onurmenal** [comment]
@mehmetseckin  I agree with you, let's leave it.

**Comment by mehmetseckin** [comment]
Closing this as the initial problems are solved. We can track further problems in their own issues during beta.
